# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\msys64\home\ebadger\EB6502\Badger6502Pico

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\msys64\home\ebadger\EB6502\Badger6502Pico

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\msys64\home\ebadger\EB6502\Badger6502Pico\CMakeFiles C:\msys64\home\ebadger\EB6502\Badger6502Pico\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\msys64\home\ebadger\EB6502\Badger6502Pico\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default_bin.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk\src\rp2_common\boot_stage2\CMakeFiles\bs2_default_padded_checksummed_asm.dir\build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

#=============================================================================
# Target rules for targets named badger6502lib

# Build rule for target.
badger6502lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 badger6502lib
.PHONY : badger6502lib

# fast build rule for target.
badger6502lib/fast:
	$(MAKE) $(MAKESILENT) -f lib\CMakeFiles\badger6502lib.dir\build.make lib/CMakeFiles/badger6502lib.dir/build
.PHONY : badger6502lib/fast

#=============================================================================
# Target rules for targets named badger6502vm

# Build rule for target.
badger6502vm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 badger6502vm
.PHONY : badger6502vm

# fast build rule for target.
badger6502vm/fast:
	$(MAKE) $(MAKESILENT) -f exe\CMakeFiles\badger6502vm.dir\build.make exe/CMakeFiles/badger6502vm.dir/build
.PHONY : badger6502vm/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f exe\CMakeFiles\ELF2UF2Build.dir\build.make exe/CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ELF2UF2Build
	@echo ... bs2_default_bin
	@echo ... bs2_default_padded_checksummed_asm
	@echo ... badger6502lib
	@echo ... badger6502vm
	@echo ... bs2_default
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

