#pragma once

#define SC_GRAVE            0x0E
#define SC_1                0x16
#define SC_2                0x1E
#define SC_3                0x26
#define SC_4                0x25
#define SC_5                0x2E
#define SC_6                0x36
#define SC_7                0x3D
#define SC_8                0x3E
#define SC_9                0x46
#define SC_0                0x45
#define SC_HYPHEN           0x4E
#define SC_EQUAL            0x55
#define SC_BACKSPACE        0x66
#define SC_TAB              0x0D
#define SC_Q                0x15
#define SC_W                0x1D
#define SC_E                0x24
#define SC_R                0x2D
#define SC_T                0x2C
#define SC_Y                0x35
#define SC_U                0x3C
#define SC_I                0x43
#define SC_O                0x44
#define SC_P                0x4D
#define SC_LEFTBRACKET      0x54
#define SC_RIGHTBRACKET     0x5B
#define SC_CAPSLOCK         0x58
#define SC_A                0x1C
#define SC_S                0x1B
#define SC_D                0x23
#define SC_F                0x2B
#define SC_G                0x34
#define SC_H                0x33
#define SC_J                0x3B
#define SC_K                0x42
#define SC_L                0x4B
#define SC_SEMICOLON        0x4C
#define SC_APOSTROPHE       0x52
#define SC_ENTER            0x5A
#define SC_LEFTSHIFT        0x12
#define SC_Z                0x1A
#define SC_X                0x22
#define SC_C                0x21
#define SC_V                0x2A
#define SC_B                0x32
#define SC_N                0x31
#define SC_M                0x3A
#define SC_COMMA            0x41
#define SC_PERIOD           0x49
#define SC_SLASH            0x4A
#define SC_RIGHTSHIFT       0x59
#define SC_LEFTCTRL         0x14
#define SC_LEFTALT          0x11
#define SC_SPACE            0x29
#define SC_RIGHTALT         0x11
#define SC_RIGHTCTRL        0x14
#define SC_INSERT           0x70
#define SC_DELETE           0x71
#define SC_LEFT             0x6B
#define SC_HOME             0x6C
#define SC_END              0x69
#define SC_UP               0x75
#define SC_DOWN             0x72
#define SC_PAGEUP           0x7D
#define SC_PAGEDOWN         0x7A
#define SC_RIGHT            0x74
#define SC_NUMLOCK          0x77
#define SC_KEYPAD_7         0x6C
#define SC_KEYPAD_4         0x6B
#define SC_KEYPAD_1         0x69
#define SC_KEYPAD_SLASH     0x4A
#define SC_KEYPAD_8         0x75
#define SC_KEYPAD_5         0x73
#define SC_KEYPAD_2         0x72
#define SC_KEYPAD_0         0x70
#define SC_KEYPAD_STAR      0x7C
#define SC_KEYPAD_9         0x7D
#define SC_KEYPAD_6         0x74
#define SC_KEYPAD_3         0x7A
#define SC_KEYPAD_PERIOD    0x71
#define SC_KEYPAD_MINUS     0x7B
#define SC_KEYPAD_PLUS      0x79
#define SC_KEYPAD_ENTER     0x5A
#define SC_ESC              0x76
#define SC_F1               0x05
#define SC_F2               0x06
#define SC_F3               0x04
#define SC_F4               0x0C
#define SC_F5               0x03
#define SC_F6               0x0B
#define SC_F7               0x83
#define SC_F8               0x0A
#define SC_F9               0x01
#define SC_F10              0x09
#define SC_F11              0x78
#define SC_F12              0x07
#define SC_PRINTSCR_MAKE    0x12 
#define SC_PRINTSCR_BREAK   0x7C
#define SC_SCROLLLOCK       0x7E
#define SC_PAUSEBREAK_MAKE  0x14 
#define SC_PAUSEBREAK_BREAK 0x77
#define SC_BACKSLASH        0x5D